export const modelsName = {
  AboutUsImage: 'AboutUsImage',
  AdminUser: 'AdminUser',
  ContactUs: 'ContactUs',
  Event: 'Event',
  Faq: 'Faq',
  EventCategory: 'EventCategory',
  JoinNowImage: 'JoinNowImage',
  MarqueImage: 'MarqueImage',
  Newsletter: 'Newsletter',
  NotificationTemplate: 'NotificationTemplate',
  Organizer: 'Organizer',
  Reply: 'Reply',
  Team: 'Team',
  User: 'User',
  Volunteer: 'Volunteer',
  VolunteerRequest: 'VolunteerRequest',
  WithdrawRequest: 'WithdrawRequest',
  SupportTicket: 'SupportTicket',
};
